# get articles
GET https://conduit.productionready.io/api/articles HTTP/1.1
###

# login
POST https://conduit.productionready.io/api/users/login HTTP/1.1
Content-Type: application/json

{
  "user":{
    "email": "gnehcyx@163.com",
    "password": "12345678"
  }
}
###

# register
POST https://conduit.productionready.io/api/users HTTP/1.1
Content-Type: application/json

{
  "user":{
    "username": "cheng",
    "email": "gnehcyx@163.com",
    "password": "12345678"
  }
}
###

# get global articles
GET  https://conduit.productionready.io/api/articles?offset=0&limit=5&tag=coffee&tag=cars&tag=dragon HTTP/1.1
Content-Type: application/json
###

# get user articles (feed)
GET  https://conduit.productionready.io/api/articles/feed?offset=0&limit=5 HTTP/1.1
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NTEwMjAsInVzZXJuYW1lIjoiY2hlbmciLCJleHAiOjE1NTkwMDc3NjZ9.5V6-9brhXeYkJAiyjhyp0y8OW3uSJA7xSZD2f31IzHo
###

# get my articles
GET  https://conduit.productionready.io/api/articles?offset=0&limit=5&author=cheng HTTP/1.1
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NTEwMjAsInVzZXJuYW1lIjoiY2hlbmciLCJleHAiOjE1NTkwMDc3NjZ9.5V6-9brhXeYkJAiyjhyp0y8OW3uSJA7xSZD2f31IzHo
###

# get favorited articles
GET  https://conduit.productionready.io/api/articles?favorited=cheng HTTP/1.1
###


# get tags
GET  https://conduit.productionready.io/api/tags HTTP/1.1
Content-Type: application/json
###